Azerbaycan dili eklendi
discordplace/discord.place pull request #46
Opened 2024-08-20 18:44 UTC by sshukurzade

2024-08-20 21:13 UTC, kardespro requested changes
In line 1889, could you change the word "anahtar" to "açar"? This would be more correct.

2024-08-21 04:29 UTC, chimpdev requested changes
config.js'yi düzenleyip AZ dilini eklemelisin

2024-08-21 04:29 UTC, chimpdev commented on client/locales/az.json
> +      "az": "Azərbaycan"
"Azərbaycanca" olması gerekmiyor mu?

2024-08-21 06:02 UTC, chimpdev requested changes

2024-08-21 06:02 UTC, chimpdev commented on client/config.js
> +     }
1 boşluk fazla koymuşsun

2024-08-21 06:07 UTC, sshukurzade commented on client/config.js
> +     }
sildim

2024-08-21 06:09 UTC, chimpdev requested changes

2024-08-21 06:09 UTC, chimpdev commented on client/config.js
> +       flag: '🇦🇿'
1 boşluk bunlardanda sil

2024-08-21 06:16 UTC, chimpdev approved these changes

2024-08-21 10:07 UTC, chimpdev approved these changes

2024-08-21 12:28 UTC, kardespro commented on client/locales/az.json
> +      "tr": "Türk",
"Türkcə" olarak deyişdirirmisin?

2024-08-21 13:44 UTC, chimpdev approved these changes

2024-08-21 13:44 UTC, merged